import {
  approvalsCellRenderer, approvalsSummaryCellRenderer, dateFilterComparator,
  isUnderInvestigationCellRenderer, numberFilterComparitor, numberFormatter,
  stpCellRenderer, stpFilterCellRenderer, timeFilterComparator, priceFormatter,
  brokerageFormatter,
} from '../../../utils/agGrid/index';
import { approveStageBlotter, enableInvestigationChkFlag } from '../../../actions/dealActions';

export default function fxColumnDefs(dispatch, permissions) {
  const headerGroups = {
    dealHeaderGroup: { headerClass: 'deal-group-header', marryChildren: true, groupId: 'deal' },
    approvalsHeaderGroup: { headerClass: 'approvals-group-header', marryChildren: true, groupId: 'approvals' },
    stpHeaderGroup: { headerClass: 'stp-group-header', marryChildren: true, groupId: 'stp' },
    brokerageHeaderGroup: { headerClass: 'brokerage-group-header', marryChildren: true, groupId: 'brokerage' },
  };

  const approvalCellRendererParams = {
    approveStageBlotter,
    dispatch,
    permissions,
  };

  return [
    {
      headerName: 'Deal',
      ...headerGroups.dealHeaderGroup,
      children: [
        {
          headerName: 'Chk',
          field: 'isDealUnderInvestigation',
          colId: 'isDealUnderInvestigation',
          cellRenderer: (params) => isUnderInvestigationCellRenderer(params),
          cellRendererParams: {
            dispatch,
            enableInvestigationChkFlag,
          },
          cellClass: 'centered',
          width: 34,
          resizable: false,
          suppressMenu: true,
          sortable: false,
        },
        {
          headerName: 'ID',
          field: 'dmsDealReference',
          colId: 'dmsDealReference',
          tooltipField: 'dmsDealReference',
          width: 85,
          lockVisible: true,
        },
        {
          headerName: 'Action',
          field: 'dealAction',
          colId: 'dealAction',
          tooltipField: 'dealAction',
          width: 74,
        },
        {
          headerName: 'Type',
          field: 'dealType',
          colId: 'dealType',
          tooltipField: 'dealType',
          width: 67,
          lockVisible: true,
        },
        {
          headerName: 'Strategy',
          field: 'tradeStrategy',
          colId: 'tradeStrategy',
          tooltipField: 'tradeStrategy',
          width: 175,
        },
        {
          headerName: 'Chain Reference',
          field: 'chainId',
          colId: 'chainId',
          tooltipField: 'chainId',
          columnGroupShow: 'open',
          width: 131,
        },
        {
          headerName: 'Trade Date',
          field: 'tradeDate',
          colId: 'tradeDate',
          tooltipField: 'tradeDate',
          columnGroupShow: 'open',
          filterParams: {
            comparator: (a, b) => dateFilterComparator(a, b),
          },
          width: 101,
        },
        {
          headerName: 'Trade Time',
          field: 'tradeTime',
          colId: 'tradeTime',
          tooltipField: 'tradeTime',
          columnGroupShow: 'open',
          filterParams: {
            comparator: (a, b) => timeFilterComparator(a, b),
          },
          width: 101,
        },
        {
          headerName: 'Value Date',
          field: 'valueDate',
          colId: 'valueDate',
          tooltipField: 'valueDate',
          columnGroupShow: 'open',
          filterParams: {
            comparator: (a, b) => dateFilterComparator(a, b),
          },
          width: 101,
        },
        {
          headerName: 'Fixing Date',
          field: 'fixingDate',
          colId: 'fixingDate',
          tooltipField: 'fixingDate',
          columnGroupShow: 'open',
          filterParams: {
            comparator: (a, b) => dateFilterComparator(a, b),
          },
          width: 101,
        },
        {
          headerName: 'Publish Date',
          field: 'publishDate',
          colId: 'publishDate',
          tooltipField: 'publishDate',
          columnGroupShow: 'open',
          filterParams: {
            comparator: (a, b) => dateFilterComparator(a, b),
          },
          width: 101,
        },
        {
          headerName: 'Venue Type',
          field: 'executionVenueType',
          colId: 'executionVenueType',
          tooltipField: 'executionVenueType',
          columnGroupShow: 'open',
          width: 104,
        },
        {
          headerName: 'Amount',
          field: 'notionalAmount',
          colId: 'notionalAmount',
          tooltipField: 'notionalAmount',
          tooltipValueGetter: (params) => numberFormatter(params.value, 2),
          columnGroupShow: 'open',
          valueFormatter: (params) => numberFormatter(params, 2),
          filterParams: {
            comparator: (a, b) => numberFilterComparitor(a, b),
          },
          width: 85,
        },
        {
          headerName: 'Price',
          field: 'price',
          colId: 'price',
          tooltipValueGetter: (params) => priceFormatter(params),
          columnGroupShow: 'open',
          valueFormatter: (params) => priceFormatter(params),
          filterParams: {
            comparator: (a, b) => numberFilterComparitor(a, b),
          },
          width: 85,
        },
        {
          headerName: 'Buy Broker',
          field: 'payerBrokerName',
          colId: 'payerBrokerName',
          tooltipField: 'payerBrokerName',
          width: 101,
        },
        {
          headerName: 'Buy Broker Long Name',
          field: 'payerBrokerLongName',
          colId: 'payerBrokerLongName',
          tooltipField: 'payerBrokerLongName',
          width: 101,
          hide: true,
        },
        {
          headerName: 'Buy Customer',
          field: 'payerCustomerName',
          colId: 'payerCustomerName',
          tooltipField: 'payerCustomerName',
          width: 121,
        },
        {
          headerName: 'Buy Customer Long Name',
          field: 'payerCustomerLongName',
          colId: 'payerCustomerLongName',
          tooltipField: 'payerCustomerLongName',
          width: 121,
          hide: true,
        },
        {
          headerName: 'Buy Trader',
          field: 'payerTraderName',
          colId: 'payerTraderName',
          tooltipField: 'payerTraderName',
          width: 101,
        },
        {
          headerName: 'Buy Trader Long Name',
          field: 'payerTraderLongName',
          colId: 'payerTraderLongName',
          tooltipField: 'payerTraderLongName',
          width: 200,
          hide: true,
        },
        {
          headerName: 'Buy Third Party Agent Name',
          field: 'payerThirdPartyAgentName',
          colId: 'payerThirdPartyAgentName',
          tooltipField: 'payerThirdPartyAgentName',
          width: 200,
          hide: true,
        },
        {
          headerName: 'Sell Broker',
          field: 'receiverBrokerName',
          colId: 'receiverBrokerName',
          tooltipField: 'receiverBrokerName',
          width: 101,
        },
        {
          headerName: 'Sell Broker Long Name',
          field: 'receiverBrokerLongName',
          colId: 'receiverBrokerLongName',
          tooltipField: 'receiverBrokerLongName',
          width: 101,
          hide: true,
        },
        {
          headerName: 'Sell Customer',
          field: 'receiverCustomerName',
          colId: 'receiverCustomerName',
          tooltipField: 'receiverCustomerName',
          width: 120,
        },
        {
          headerName: 'Sell Customer Long Name',
          field: 'receiverCustomerLongName',
          colId: 'receiverCustomerLongName',
          tooltipField: 'receiverCustomerLongName',
          width: 120,
          hide: true,
        },
        {
          headerName: 'Sell Trader',
          field: 'receiverTraderName',
          colId: 'receiverTraderName',
          tooltipField: 'receiverTraderName',
          width: 99,
        },
        {
          headerName: 'Sell Trader Long Name',
          field: 'receiverTraderLongName',
          colId: 'receiverTraderLongName',
          tooltipField: 'receiverTraderLongName',
          width: 200,
          hide: true,
        },
        {
          headerName: 'Sell Third Party Agent Name',
          field: 'receiverThirdPartyAgentName',
          colId: 'receiverThirdPartyAgentName',
          tooltipField: 'receiverThirdPartyAgentName',
          width: 200,
          hide: true,
        },
        {
          headerName: 'Status',
          field: 'dealStatus',
          colId: 'dealStatus',
          tooltipField: 'dealStatus',
          width: 91,
        },
      ],
    },
    {
      headerName: 'Approvals',
      ...headerGroups.approvalsHeaderGroup,
      children: [
        {
          ...headerGroups.approvalsHeaderGroup,
          headerName: 'Buy',
          field: 'payerOverallApprovalStatus',
          colId: 'payerOverallApprovalStatus',
          columnGroupShow: 'closed',
          cellRenderer: (params) => approvalsSummaryCellRenderer(params),
          cellRendererParams: { side: 'PAYER' },
          lockPinned: true,
          width: 103,
        },
        {
          ...headerGroups.approvalsHeaderGroup,
          headerName: 'Sell',
          field: 'receiverOverallApprovalStatus',
          colId: 'receiverOverallApprovalStatus',
          columnGroupShow: 'closed',
          cellRenderer: (params) => approvalsSummaryCellRenderer(params),
          cellRendererParams: { side: 'RECEIVER' },
          lockPinned: true,
          width: 103,
        },
        {
          ...headerGroups.approvalsHeaderGroup,
          headerName: 'Buy Broker',
          field: 'payerBrokerApprovalState',
          colId: 'payerBrokerApprovalState',
          columnGroupShow: 'open',
          cellRenderer: (params) => approvalsCellRenderer(params),
          cellRendererParams: {
            ...approvalCellRendererParams,
            side: 'PAYER',
            position: 'BROKER',
          },
          width: 100,
        },
        {
          ...headerGroups.approvalsHeaderGroup,
          headerName: 'Buy Mid-Office',
          field: 'payerMidOfficeApprovalState',
          colId: 'payerMidOfficeApprovalState',
          columnGroupShow: 'open',
          cellRenderer: (params) => approvalsCellRenderer(params),
          cellRendererParams: {
            ...approvalCellRendererParams,
            side: 'PAYER',
            position: 'MID_OFFICE',
          },
          width: 119,
        },
        {
          ...headerGroups.approvalsHeaderGroup,
          headerName: 'Buy Trader',
          field: 'payerTraderApprovalState',
          colId: 'payerTraderApprovalState',
          columnGroupShow: 'open',
          cellRenderer: (params) => approvalsCellRenderer(params),
          cellRendererParams: {
            ...approvalCellRendererParams,
            side: 'PAYER',
            position: 'TRADER',
          },
          width: 100,
        },
        {
          ...headerGroups.approvalsHeaderGroup,
          headerName: 'Sell Broker',
          field: 'receiverBrokerApprovalState',
          colId: 'receiverBrokerApprovalState',
          columnGroupShow: 'open',
          cellRenderer: (params) => approvalsCellRenderer(params),
          cellRendererParams: {
            ...approvalCellRendererParams,
            side: 'RECEIVER',
            position: 'BROKER',
          },
          width: 100,
        },
        {
          ...headerGroups.approvalsHeaderGroup,
          headerName: 'Sell Mid-Office',
          field: 'receiverMidOfficeApprovalState',
          colId: 'receiverMidOfficeApprovalState',
          columnGroupShow: 'open',
          cellRenderer: (params) => approvalsCellRenderer(params),
          cellRendererParams: {
            ...approvalCellRendererParams,
            side: 'RECEIVER',
            position: 'MID_OFFICE',
          },
          width: 118,
        },
        {
          ...headerGroups.approvalsHeaderGroup,
          headerName: 'Sell Trader',
          field: 'receiverTraderApprovalState',
          colId: 'receiverTraderApprovalState',
          columnGroupShow: 'open',
          cellRenderer: (params) => approvalsCellRenderer(params),
          cellRendererParams: {
            ...approvalCellRendererParams,
            side: 'RECEIVER',
            position: 'TRADER',
          },
          width: 99,
        },
      ],
    },
    {
      headerName: 'STP',
      ...headerGroups.stpHeaderGroup,
      children: [
        {
          ...headerGroups.stpHeaderGroup,
          headerName: 'Buy',
          field: 'payerSTPStatusGroup',
          colId: 'payerSTPStatusGroup',
          cellRenderer: (params) => stpCellRenderer(params),
          cellRendererParams: { side: 'PAYER' },
          filterParams: {
            cellRenderer: (params) => stpFilterCellRenderer(params),
          },
          width: 61,
        },
        {
          ...headerGroups.stpHeaderGroup,
          headerName: 'Sell',
          field: 'receiverSTPStatusGroup',
          colId: 'receiverSTPStatusGroup',
          cellRenderer: (params) => stpCellRenderer(params),
          cellRendererParams: { side: 'RECEIVER' },
          filterParams: {
            cellRenderer: (params) => stpFilterCellRenderer(params),
          },
          width: 61,
        },
      ],
    },
    {
      headerName: 'Brokerage',
      ...headerGroups.brokerageHeaderGroup,
      children: [
        {
          ...headerGroups.brokerageHeaderGroup,
          headerName: 'Buy CCY',
          field: 'payerBrokerageCurrency',
          colId: 'payerBrokerageCurrency',
          tooltipField: 'payerBrokerageCurrency',
          width: 91,
        },
        {
          ...headerGroups.brokerageHeaderGroup,
          headerName: 'Buy Amount',
          field: 'payerBrokerageAmount',
          colId: 'payerBrokerageAmount',
          tooltipField: 'payerBrokerageAmount',
          cellRenderer: (params) => brokerageFormatter(params),
          filterParams: {
            comparator: (a, b) => numberFilterComparitor(a, b),
          },
          width: 106,
        },
        {
          ...headerGroups.brokerageHeaderGroup,
          headerName: 'Buy Std CCY',
          field: 'payerBrokerageStdCurrency',
          colId: 'payerBrokerageStdCurrency',
          tooltipField: 'payerBrokerageStdCurrency',
          columnGroupShow: 'open',
          width: 111,
        },
        {
          ...headerGroups.brokerageHeaderGroup,
          headerName: 'Buy Std Amount',
          field: 'payerBrokerageStdAmount',
          colId: 'payerBrokerageStdAmount',
          tooltipField: 'payerBrokerageStdAmount',
          columnGroupShow: 'open',
          cellRenderer: (params) => brokerageFormatter(params),
          filterParams: {
            comparator: (a, b) => numberFilterComparitor(a, b),
          },
          width: 131,
        },
        {
          ...headerGroups.brokerageHeaderGroup,
          headerName: 'Sell CCY',
          field: 'receiverBrokerageCurrency',
          colId: 'receiverBrokerageCurrency',
          tooltipField: 'receiverBrokerageCurrency',
          width: 89,
        },
        {
          ...headerGroups.brokerageHeaderGroup,
          headerName: 'Sell Amount',
          field: 'receiverBrokerageAmount',
          colId: 'receiverBrokerageAmount',
          tooltipField: 'receiverBrokerageAmount',
          cellRenderer: (params) => brokerageFormatter(params),
          filterParams: {
            comparator: (a, b) => numberFilterComparitor(a, b),
          },
          width: 106,
        },
        {
          ...headerGroups.brokerageHeaderGroup,
          headerName: 'Sell Std CCY',
          field: 'receiverBrokerageStdCurrency',
          colId: 'receiverBrokerageStdCurrency',
          tooltipField: 'receiverBrokerageStdCurrency',
          columnGroupShow: 'open',
          width: 111,
        },
        {
          ...headerGroups.brokerageHeaderGroup,
          headerName: 'Sell Std Amount',
          field: 'receiverBrokerageStdAmount',
          colId: 'receiverBrokerageStdAmount',
          tooltipField: 'receiverBrokerageStdAmount',
          columnGroupShow: 'open',
          cellRenderer: (params) => brokerageFormatter(params),
          filterParams: {
            comparator: (a, b) => numberFilterComparitor(a, b),
          },
          width: 131,
        },
      ],
    },
  ];
}
